const express=require('express')
const searchFood = require('../controller/searchFood')
const searchActivity = require('../controller/searchActivity')
const addData = require('../controller/addUserData')
const getUserData = require('../controller/getUserData')
const getUserDataofToday = require('../controller/getUserDataofToday')
const getAllFood = require('../controller/getAllFood')
const getAllActivity = require('../controller/getAllActivity')
const getUserDatabyDate = require('../controller/getUserDatabyDate')
const removeData = require('../controller/removeUserData')
const getUserDatabyWeek = require('../controller/getUserDatabyWeek')
const getxpbyuseruid = require('../controller/getxpbyuseruid')
const xpleaderboard = require('../controller/xpleaderboard')
const router=express.Router()

router.get('/food',searchFood)
router.get('/activity',searchActivity)
router.post('/add',addData)
router.get('/user/:uid',getUserData)
router.get('/user/date/:uid',getUserDatabyDate)
router.get('/user/today/:uid',getUserDataofToday)
router.get('/getallfood',getAllFood)
router.get('/getallactivity',getAllActivity)
router.delete('/delete/:id',removeData)
router.get('/week/:id',getUserDatabyWeek)
router.get('/xp/:uid',getxpbyuseruid)
router.get('/leaderboard',xpleaderboard)

module.exports=router