// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcxvqSs_4ljICnivvaHgW8IbGsVJsSDzs',
    appId: '1:426649024006:web:5822eb77d5c78ea0e6b587',
    messagingSenderId: '426649024006',
    projectId: 'aquatrace-d47ce',
    authDomain: 'aquatrace-d47ce.firebaseapp.com',
    storageBucket: 'aquatrace-d47ce.appspot.com',
    measurementId: 'G-BJCZLJEHN1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5HSGHl3ihPF2T9QCqNGHBwW4uVHe2ee0',
    appId: '1:426649024006:android:b4df7100b87ed9f9e6b587',
    messagingSenderId: '426649024006',
    projectId: 'aquatrace-d47ce',
    storageBucket: 'aquatrace-d47ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyHbk2TUSAc8vavn62YksynCVYUModxY0',
    appId: '1:426649024006:ios:bde3af96aa1ac3b5e6b587',
    messagingSenderId: '426649024006',
    projectId: 'aquatrace-d47ce',
    storageBucket: 'aquatrace-d47ce.appspot.com',
    iosBundleId: 'com.example.aquaTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyHbk2TUSAc8vavn62YksynCVYUModxY0',
    appId: '1:426649024006:ios:1b43c7e254b6ff21e6b587',
    messagingSenderId: '426649024006',
    projectId: 'aquatrace-d47ce',
    storageBucket: 'aquatrace-d47ce.appspot.com',
    iosBundleId: 'com.example.aquaTrace.RunnerTests',
  );
}
